eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://192.168.99.1:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8761
spring:
  application:
    name: eureka-service
